# model-monitoring-with-collected-data.yaml
$schema:  http://azureml/sdk-2-0/Schedule.json
name: default_credit_card_prediction
display_name: default credit card model monitoring
description: default credit card model monitoring with your own production data

trigger:
  # perform model monitoring activity daily at 3:15am
  type: recurrence
  frequency: day #can be minute, hour, day, week, month
  interval: 1 # #every day
  schedule: 
    hours: 3 # at 3am
    minutes: 15 # at 15 mins after 3am

create_monitor:
  compute: 
    instance_type: standard_e4s_v3
    runtime_version: "3.4"
  monitoring_target:
    ml_task: classification
  
  monitoring_signals:
    advanced_prediction_drift: # monitoring signal name, any user defined name works
      type: prediction_drift
      # define production dataset with your collected data
      production_data:
        input_data:
          path: azureml:credit-default-output-folder:1  # your collected data is registered as Azure Machine Learning asset
          type: uri_folder
        data_context: model_outputs
        pre_processing_component: azureml:custom_preprocessor:2.13.0
      reference_data:
        input_data:
          path: azureml:credit-default-reference:1 # use training data as comparison reference dataset
          type: mltable
        data_context: validation
      alert_enabled: false
      metric_thresholds:
        categorical:
          pearsons_chi_squared_test: 0.02
    # advanced_data_drift: # monitoring signal name, any user defined name works
    #   type: data_drift
      
    #   # define production dataset with your collected data
    #   production_data:
    #     input_data:
    #       path: azureml:credit-default-output-folder:1  # your collected data is registered as Azure Machine Learning asset
    #       type: uri_folder
    #     data_context: model_inputs
    #     pre_processing_component: azureml:custom_preprocessor:2.13.0

        
    #   reference_data:
    #     input_data:
    #       path: azureml:credit-default-reference:1 # use training data as comparison baseline
    #       type: mltable
    #     # data_context: training
    #     data_column_names:
    #       target_column: DEFAULT_NEXT_MONTH
    #   features: 
    #     top_n_feature_importance: 20 # monitor drift for top 20 features
    #   alert_enabled: false
    #   metric_thresholds:
    #     numerical:
    #       jensen_shannon_distance: 0.01
    #     categorical:
    #       pearsons_chi_squared_test: 0.02

  
